// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * V​o​x​M​e​t​r​i​c
	 */
	App: string
	Roles: {
		/**
		 * A​d​m​i​n
		 */
		Admin: string
		/**
		 * P​a​r​t​i​c​i​p​a​n​t
		 */
		Participant: string
	}
	Login: {
		/**
		 * H​e​l​l​o​,​ ​i​n​s​e​r​t​ ​y​o​u​r​ ​c​r​e​d​e​n​t​i​a​l​s​ ​t​o​ ​l​o​g​i​n​.
		 */
		Title: string
		Placeholders: {
			/**
			 * E​m​a​i​l
			 */
			Email: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			Password: string
		}
	}
	SignUp: {
		/**
		 * L​e​t​'​s​ ​c​r​e​a​t​e​ ​y​o​u​r​ ​c​r​e​d​e​n​t​i​a​l​s​.
		 */
		AccountTitle: string
		/**
		 * W​e​l​c​o​m​e​,​ ​t​e​l​l​ ​u​s​ ​w​h​o​ ​y​o​u​ ​a​r​e​.
		 */
		PersonalTitle: string
		Placeholders: {
			/**
			 * N​a​m​e
			 */
			Name: string
			/**
			 * U​s​e​r​n​a​m​e
			 */
			Username: string
			/**
			 * I​n​s​t​i​t​u​t​i​o​n
			 */
			Institution: string
			/**
			 * P​h​o​n​e
			 */
			Phone: string
			/**
			 * E​m​a​i​l
			 */
			Email: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			Password: string
			/**
			 * A​b​o​u​t​ ​y​o​u​ ​.​.​.​ ​p​u​r​p​o​s​e​s​ ​.​.​.
			 */
			Description: string
			/**
			 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
			 */
			ConfirmPassword: string
		}
	}
	Forms: {
		/**
		 * F​o​r​m​s
		 */
		Title: string
		/**
		 * M​a​n​a​g​e​ ​f​o​r​m​s​ ​a​n​d​ ​r​e​s​u​l​t​s​.
		 */
		Subtitle: string
		Filters: {
			/**
			 * A​l​l
			 */
			All: string
			/**
			 * I​n​ ​U​s​e
			 */
			InUse: string
			/**
			 * S​t​a​t​u​s
			 */
			Status: string
			/**
			 * D​i​s​a​b​l​e​d
			 */
			Disabled: string
			/**
			 * E​n​a​b​l​e​d
			 */
			Enabled: string
		}
		Headers: {
			/**
			 * I​D
			 */
			ID: string
			/**
			 * A​l​i​a​s
			 */
			Alias: string
			/**
			 * I​t​e​m​s
			 */
			Items: string
			/**
			 * U​s​e​d​ ​i​n
			 */
			UsedIn: string
			/**
			 * R​e​s​u​l​t​s
			 */
			Results: string
			/**
			 * S​t​a​t​u​s
			 */
			Status: string
			/**
			 * C​r​e​a​t​e​d​ ​a​t
			 */
			CreatedAt: string
			/**
			 * A​c​t​i​o​n​s
			 */
			Actions: string
		}
		Buttons: {
			/**
			 * B​u​i​l​d
			 */
			Build: string
		}
	}
	Medias: {
		/**
		 * M​e​d​i​a​s
		 */
		Title: string
		/**
		 * S​e​e​ ​a​l​l​ ​y​o​u​r​ ​i​m​a​g​e​s​ ​a​n​d​ ​a​u​d​i​o​ ​f​i​l​e​s​.
		 */
		Subtitle: string
		Filters: {
			/**
			 * A​l​l
			 */
			All: string
			/**
			 * A​u​d​i​o
			 */
			Audio: string
			/**
			 * I​m​a​g​e
			 */
			Image: string
			/**
			 * I​n​ ​U​s​e
			 */
			InUse: string
			/**
			 * N​a​m​e
			 */
			Name: string
			/**
			 * S​i​z​e
			 */
			Size: string
		}
	}
	Build: {
		/**
		 * B​u​i​l​d
		 */
		Title: string
		/**
		 * P​a​n​e​l​ ​t​o​ ​c​r​e​a​t​e​ ​s​c​r​e​e​n​s​ ​a​n​d​ ​f​o​r​m​s​.
		 */
		Subtitle: string
		Filters: {
			/**
			 * A​l​l
			 */
			All: string
			/**
			 * M​i​n​e
			 */
			Mine: string
		}
		Headers: {
			/**
			 * I​D
			 */
			ID: string
			/**
			 * A​l​i​a​s
			 */
			Alias: string
			/**
			 * E​x​p​e​r​i​m​e​n​t​s
			 */
			Experiments: string
			/**
			 * U​s​e​d​ ​i​n
			 */
			UsedIn: string
			/**
			 * S​t​a​t​u​s
			 */
			Status: string
			/**
			 * C​r​e​a​t​e​d​ ​a​t
			 */
			CreatedAt: string
			/**
			 * P​a​r​t​i​c​i​p​a​n​t​s
			 */
			Participants: string
			/**
			 * A​c​t​i​o​n​s
			 */
			Actions: string
		}
	}
	Modals: {
		MediaViewer: {
			/**
			 * M​e​d​i​a​ ​V​i​e​w​e​r
			 */
			Title: string
			Details: {
				/**
				 * D​e​t​a​i​l​s
				 */
				Subtitle: string
				/**
				 * T​y​p​e
				 */
				Type: string
				/**
				 * F​i​l​e​n​a​m​e
				 */
				Filename: string
				/**
				 * S​i​z​e
				 */
				Size: string
				/**
				 * U​p​l​o​a​d​e​d​ ​a​t
				 */
				UploadAt: string
				/**
				 * U​R​L
				 */
				URL: string
				/**
				 * U​s​e​d​ ​i​n
				 */
				UsedIn: string
				/**
				 * E​x​t​e​n​s​i​o​n
				 */
				Extension: string
			}
			/**
			 * o​f​ ​{​t​o​t​a​l​}​ ​m​e​d​i​a​s
			 * @param {unknown} total
			 */
			Of: RequiredParams<'total'>
		}
		AppSettings: {
			/**
			 * L​a​n​g​u​a​g​e
			 */
			Language: string
			/**
			 * C​h​a​n​g​e​ ​a​p​p​l​i​c​a​t​i​o​n​ ​l​a​n​g​u​a​g​e
			 */
			ChangeLanguage: string
			/**
			 * T​h​e​m​e
			 */
			Theme: string
			/**
			 * C​h​a​n​g​e​ ​a​p​p​l​i​c​a​t​i​o​n​ ​a​p​p​e​a​r​a​n​c​e
			 */
			ChangeTheme: string
			/**
			 * L​i​g​h​t
			 */
			Light: string
			/**
			 * D​a​r​k
			 */
			Dark: string
		}
		Upload: {
			/**
			 * U​p​l​o​a​d​ ​F​i​l​e​s
			 */
			Title: string
			/**
			 * D​r​a​g​ ​a​n​d​ ​d​r​o​p​ ​f​i​l​e​s​ ​h​e​r​e​,​ ​o​r​ ​c​l​i​c​k​ ​t​o​ ​s​e​l​e​c​t​ ​f​i​l​e​s
			 */
			DragAndDrop: string
			/**
			 * S​e​l​e​c​t​ ​F​i​l​e​s
			 */
			SelectFiles: string
			/**
			 * S​e​l​e​c​t​e​d​ ​F​i​l​e​s​ ​(​{​c​o​u​n​t​}​)
			 * @param {unknown} count
			 */
			SelectedFiles: RequiredParams<'count'>
			/**
			 * C​l​e​a​r​ ​A​l​l
			 */
			ClearAll: string
			/**
			 * S​u​p​p​o​r​t​e​d​ ​f​o​r​m​a​t​s​:​ ​A​u​d​i​o​ ​(​M​P​3​,​ ​W​A​V​,​ ​e​t​c​.​)​ ​a​n​d​ ​I​m​a​g​e​s​ ​(​J​P​G​,​ ​P​N​G​,​ ​e​t​c​.​)
			 */
			SupportedFormats: string
		}
	}
	Buttons: {
		/**
		 * N​e​x​t
		 */
		Next: string
		/**
		 * B​a​c​k
		 */
		Back: string
		/**
		 * S​u​b​m​i​t
		 */
		Submit: string
		/**
		 * E​n​t​e​r
		 */
		Enter: string
		/**
		 * U​p​l​o​a​d
		 */
		Upload: string
		/**
		 * D​o​w​n​l​o​a​d
		 */
		Download: string
		/**
		 * D​e​l​e​t​e
		 */
		Delete: string
		/**
		 * N​e​w
		 */
		New: string
	}
	Sidebar: {
		/**
		 * S​e​a​r​c​h
		 */
		Search: string
		Nav: {
			/**
			 * P​r​o​j​e​c​t​s
			 */
			Projects: string
			/**
			 * M​e​d​i​a​s
			 */
			Medias: string
			/**
			 * F​o​r​m​s
			 */
			Forms: string
			/**
			 * B​u​i​l​d
			 */
			Build: string
		}
	}
	Breadcrumbs: {
		/**
		 * A​d​m​i​n
		 */
		admin: string
		/**
		 * P​r​o​j​e​c​t​s
		 */
		projects: string
		/**
		 * M​e​d​i​a​s
		 */
		medias: string
		/**
		 * F​o​r​m​s
		 */
		forms: string
		/**
		 * B​u​i​l​d
		 */
		builder: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * E​d​i​t
		 */
		edit: string
	}
	SystemErrors: {
		/**
		 * I​n​v​a​l​i​d​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​.
		 */
		InvalidEmail: string
		/**
		 * P​a​s​s​w​o​r​d​ ​d​o​e​s​ ​n​o​t​ ​m​e​e​t​ ​t​h​e​ ​r​e​q​u​i​r​e​m​e​n​t​s​.​ ​M​i​n​ ​{​m​i​n​L​e​n​g​t​h​}​ ​c​h​a​r​a​c​t​e​r​s​,​ ​a​t​ ​l​e​a​s​t​.
		 * @param {unknown} minLength
		 */
		InvalidPassword: RequiredParams<'minLength'>
		/**
		 * P​a​s​s​w​o​r​d​s​ ​d​o​ ​n​o​t​ ​m​a​t​c​h​.
		 */
		InvalidConfirmPassword: string
		/**
		 * T​h​e​ ​f​i​e​l​d​ ​{​n​a​m​e​}​ ​i​s​ ​r​e​q​u​i​r​e​d​.
		 * @param {unknown} name
		 */
		RequiredField: RequiredParams<'name'>
		/**
		 * T​h​i​s​ ​e​m​a​i​l​ ​i​s​ ​a​l​r​e​a​d​y​ ​r​e​g​i​s​t​e​r​e​d​.
		 */
		EmailAlreadyExists: string
		/**
		 * T​h​i​s​ ​u​s​e​r​n​a​m​e​ ​i​s​ ​a​l​r​e​a​d​y​ ​t​a​k​e​n​.
		 */
		UsernameAlreadyExists: string
	}
	Links: {
		/**
		 * S​i​g​n​ ​U​p
		 */
		SignUp: string
		/**
		 * L​o​g​i​n
		 */
		Login: string
	}
	UserControl: {
		/**
		 * L​o​g​o​u​t
		 */
		Logout: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		Settings: string
	}
	Languages: {
		/**
		 * E​n​g​l​i​s​h
		 */
		English: string
		/**
		 * P​o​r​t​u​g​u​ê​s
		 */
		Portuguese: string
	}
}

export type TranslationFunctions = {
	/**
	 * VoxMetric
	 */
	App: () => LocalizedString
	Roles: {
		/**
		 * Admin
		 */
		Admin: () => LocalizedString
		/**
		 * Participant
		 */
		Participant: () => LocalizedString
	}
	Login: {
		/**
		 * Hello, insert your credentials to login.
		 */
		Title: () => LocalizedString
		Placeholders: {
			/**
			 * Email
			 */
			Email: () => LocalizedString
			/**
			 * Password
			 */
			Password: () => LocalizedString
		}
	}
	SignUp: {
		/**
		 * Let's create your credentials.
		 */
		AccountTitle: () => LocalizedString
		/**
		 * Welcome, tell us who you are.
		 */
		PersonalTitle: () => LocalizedString
		Placeholders: {
			/**
			 * Name
			 */
			Name: () => LocalizedString
			/**
			 * Username
			 */
			Username: () => LocalizedString
			/**
			 * Institution
			 */
			Institution: () => LocalizedString
			/**
			 * Phone
			 */
			Phone: () => LocalizedString
			/**
			 * Email
			 */
			Email: () => LocalizedString
			/**
			 * Password
			 */
			Password: () => LocalizedString
			/**
			 * About you ... purposes ...
			 */
			Description: () => LocalizedString
			/**
			 * Confirm Password
			 */
			ConfirmPassword: () => LocalizedString
		}
	}
	Forms: {
		/**
		 * Forms
		 */
		Title: () => LocalizedString
		/**
		 * Manage forms and results.
		 */
		Subtitle: () => LocalizedString
		Filters: {
			/**
			 * All
			 */
			All: () => LocalizedString
			/**
			 * In Use
			 */
			InUse: () => LocalizedString
			/**
			 * Status
			 */
			Status: () => LocalizedString
			/**
			 * Disabled
			 */
			Disabled: () => LocalizedString
			/**
			 * Enabled
			 */
			Enabled: () => LocalizedString
		}
		Headers: {
			/**
			 * ID
			 */
			ID: () => LocalizedString
			/**
			 * Alias
			 */
			Alias: () => LocalizedString
			/**
			 * Items
			 */
			Items: () => LocalizedString
			/**
			 * Used in
			 */
			UsedIn: () => LocalizedString
			/**
			 * Results
			 */
			Results: () => LocalizedString
			/**
			 * Status
			 */
			Status: () => LocalizedString
			/**
			 * Created at
			 */
			CreatedAt: () => LocalizedString
			/**
			 * Actions
			 */
			Actions: () => LocalizedString
		}
		Buttons: {
			/**
			 * Build
			 */
			Build: () => LocalizedString
		}
	}
	Medias: {
		/**
		 * Medias
		 */
		Title: () => LocalizedString
		/**
		 * See all your images and audio files.
		 */
		Subtitle: () => LocalizedString
		Filters: {
			/**
			 * All
			 */
			All: () => LocalizedString
			/**
			 * Audio
			 */
			Audio: () => LocalizedString
			/**
			 * Image
			 */
			Image: () => LocalizedString
			/**
			 * In Use
			 */
			InUse: () => LocalizedString
			/**
			 * Name
			 */
			Name: () => LocalizedString
			/**
			 * Size
			 */
			Size: () => LocalizedString
		}
	}
	Build: {
		/**
		 * Build
		 */
		Title: () => LocalizedString
		/**
		 * Panel to create screens and forms.
		 */
		Subtitle: () => LocalizedString
		Filters: {
			/**
			 * All
			 */
			All: () => LocalizedString
			/**
			 * Mine
			 */
			Mine: () => LocalizedString
		}
		Headers: {
			/**
			 * ID
			 */
			ID: () => LocalizedString
			/**
			 * Alias
			 */
			Alias: () => LocalizedString
			/**
			 * Experiments
			 */
			Experiments: () => LocalizedString
			/**
			 * Used in
			 */
			UsedIn: () => LocalizedString
			/**
			 * Status
			 */
			Status: () => LocalizedString
			/**
			 * Created at
			 */
			CreatedAt: () => LocalizedString
			/**
			 * Participants
			 */
			Participants: () => LocalizedString
			/**
			 * Actions
			 */
			Actions: () => LocalizedString
		}
	}
	Modals: {
		MediaViewer: {
			/**
			 * Media Viewer
			 */
			Title: () => LocalizedString
			Details: {
				/**
				 * Details
				 */
				Subtitle: () => LocalizedString
				/**
				 * Type
				 */
				Type: () => LocalizedString
				/**
				 * Filename
				 */
				Filename: () => LocalizedString
				/**
				 * Size
				 */
				Size: () => LocalizedString
				/**
				 * Uploaded at
				 */
				UploadAt: () => LocalizedString
				/**
				 * URL
				 */
				URL: () => LocalizedString
				/**
				 * Used in
				 */
				UsedIn: () => LocalizedString
				/**
				 * Extension
				 */
				Extension: () => LocalizedString
			}
			/**
			 * of {total} medias
			 */
			Of: (arg: { total: unknown }) => LocalizedString
		}
		AppSettings: {
			/**
			 * Language
			 */
			Language: () => LocalizedString
			/**
			 * Change application language
			 */
			ChangeLanguage: () => LocalizedString
			/**
			 * Theme
			 */
			Theme: () => LocalizedString
			/**
			 * Change application appearance
			 */
			ChangeTheme: () => LocalizedString
			/**
			 * Light
			 */
			Light: () => LocalizedString
			/**
			 * Dark
			 */
			Dark: () => LocalizedString
		}
		Upload: {
			/**
			 * Upload Files
			 */
			Title: () => LocalizedString
			/**
			 * Drag and drop files here, or click to select files
			 */
			DragAndDrop: () => LocalizedString
			/**
			 * Select Files
			 */
			SelectFiles: () => LocalizedString
			/**
			 * Selected Files ({count})
			 */
			SelectedFiles: (arg: { count: unknown }) => LocalizedString
			/**
			 * Clear All
			 */
			ClearAll: () => LocalizedString
			/**
			 * Supported formats: Audio (MP3, WAV, etc.) and Images (JPG, PNG, etc.)
			 */
			SupportedFormats: () => LocalizedString
		}
	}
	Buttons: {
		/**
		 * Next
		 */
		Next: () => LocalizedString
		/**
		 * Back
		 */
		Back: () => LocalizedString
		/**
		 * Submit
		 */
		Submit: () => LocalizedString
		/**
		 * Enter
		 */
		Enter: () => LocalizedString
		/**
		 * Upload
		 */
		Upload: () => LocalizedString
		/**
		 * Download
		 */
		Download: () => LocalizedString
		/**
		 * Delete
		 */
		Delete: () => LocalizedString
		/**
		 * New
		 */
		New: () => LocalizedString
	}
	Sidebar: {
		/**
		 * Search
		 */
		Search: () => LocalizedString
		Nav: {
			/**
			 * Projects
			 */
			Projects: () => LocalizedString
			/**
			 * Medias
			 */
			Medias: () => LocalizedString
			/**
			 * Forms
			 */
			Forms: () => LocalizedString
			/**
			 * Build
			 */
			Build: () => LocalizedString
		}
	}
	Breadcrumbs: {
		/**
		 * Admin
		 */
		admin: () => LocalizedString
		/**
		 * Projects
		 */
		projects: () => LocalizedString
		/**
		 * Medias
		 */
		medias: () => LocalizedString
		/**
		 * Forms
		 */
		forms: () => LocalizedString
		/**
		 * Build
		 */
		builder: () => LocalizedString
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
	}
	SystemErrors: {
		/**
		 * Invalid email address.
		 */
		InvalidEmail: () => LocalizedString
		/**
		 * Password does not meet the requirements. Min {minLength} characters, at least.
		 */
		InvalidPassword: (arg: { minLength: unknown }) => LocalizedString
		/**
		 * Passwords do not match.
		 */
		InvalidConfirmPassword: () => LocalizedString
		/**
		 * The field {name} is required.
		 */
		RequiredField: (arg: { name: unknown }) => LocalizedString
		/**
		 * This email is already registered.
		 */
		EmailAlreadyExists: () => LocalizedString
		/**
		 * This username is already taken.
		 */
		UsernameAlreadyExists: () => LocalizedString
	}
	Links: {
		/**
		 * Sign Up
		 */
		SignUp: () => LocalizedString
		/**
		 * Login
		 */
		Login: () => LocalizedString
	}
	UserControl: {
		/**
		 * Logout
		 */
		Logout: () => LocalizedString
		/**
		 * Settings
		 */
		Settings: () => LocalizedString
	}
	Languages: {
		/**
		 * English
		 */
		English: () => LocalizedString
		/**
		 * Português
		 */
		Portuguese: () => LocalizedString
	}
}

export type Formatters = {}
